#!/bin/bash

function _env {
  local env

  if [[ -n "$1" ]]; then
    env="$1"
  else
    env=".env"
  fi

  splitenvs "$env" --lines
}

function tailwind {
  : "Run tailwind in watch mode"
  tailwindcss \
    --input=flaskr/static/app.tailwind.cs \
    --output=flaskr/static/app.css \
    --config=tailwind.config.js \
    --watch
}

function flask {
  : "Start flask development server"
  : "Usage:"
  : "    run flask env_filename"
  : "    run flask"
  eval "$(_env "$1") poetry run flask run"
}

function dev {
  : "Run development tasks"
  : "Usage:"
  : "    run dev env_filename"
  : "    run dev"
  tailwind &
  flask "$@" &
  wait
}

function help {
  : "List tasks"
  compgen -A function | grep -v "^_" | while read -r name; do
    paste <(printf '%s' "$name") <(type "$name" | sed -nEe 's/^[[:space:]]*: ?"(.*)";/    \1/p')
  done

  printf "\n"
}

TIMEFORMAT="Task completed in %3lR"
time "${@:-help}"
